// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list_students.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/shared.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
async function requireAdmin(ctx) {
  if (!ctx.isAuthenticated()) {
    return {
      content: [{ type: "text", text: "Not authenticated" }],
      isError: true
    };
  }
  const supabase = createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
  const { data, error } = await supabase.rpc("has_role", {
    _user_id: ctx.getUserId(),
    _role: "admin"
  });
  if (error) {
    return {
      content: [{ type: "text", text: `Authorization check failed: ${error.message}` }],
      isError: true
    };
  }
  if (!data) {
    return {
      content: [
        {
          type: "text",
          text: "Access denied: this MCP server is restricted to school admins."
        }
      ],
      isError: true
    };
  }
  return null;
}

// src/lib/mcp/tools/list_students.ts
var list_students_default = defineTool({
  name: "list_students",
  title: "List students",
  description: "List students in the school, optionally filtered by class name. Returns registration number, full name, and class.",
  inputSchema: {
    class_name: z.string().optional().describe("Optional class name filter, e.g. 'Form 1' or 'Class 8'."),
    limit: z.number().int().min(1).max(500).optional().describe("Max rows to return (default 200).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ class_name, limit }, ctx) => {
    const gate = await requireAdmin(ctx);
    if (gate) return gate;
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let query = supabase.from("students").select("registration_number, full_name, classes(name)").order("full_name").limit(limit ?? 200);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((s) => ({
      registration_number: s.registration_number,
      full_name: s.full_name,
      class: s.classes?.name ?? null
    })).filter((s) => !class_name || (s.class ?? "").toLowerCase() === class_name.toLowerCase());
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { students: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/list_classes.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_classes_default = defineTool2({
  name: "list_classes",
  title: "List classes",
  description: "List all class levels in the school with student counts.",
  inputSchema: {},
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const gate = await requireAdmin(ctx);
    if (gate) return gate;
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("classes").select("id, name, students(count)").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((c) => ({
      id: c.id,
      name: c.name,
      student_count: c.students?.[0]?.count ?? 0
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { classes: rows }
    };
  }
});

// src/lib/mcp/tools/get_student_results.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_student_results_default = defineTool3({
  name: "get_student_results",
  title: "Get student results",
  description: "Get Term 1 results for a specific student by registration number. Returns subject, mark, and academic year.",
  inputSchema: {
    registration_number: z2.string().trim().min(1).describe("Student registration number."),
    academic_year: z2.string().optional().describe("Optional academic year filter, format YYYY-YYYY.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ registration_number, academic_year }, ctx) => {
    const gate = await requireAdmin(ctx);
    if (gate) return gate;
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data: student, error: sErr } = await supabase.from("students").select("id, full_name, classes(name)").eq("registration_number", registration_number).maybeSingle();
    if (sErr) return { content: [{ type: "text", text: sErr.message }], isError: true };
    if (!student)
      return { content: [{ type: "text", text: "Student not found" }], isError: true };
    let q = supabase.from("results").select("term1, academic_year, subjects(name)").eq("student_id", student.id);
    if (academic_year) q = q.eq("academic_year", academic_year);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const results = (data ?? []).map((r) => ({
      subject: r.subjects?.name,
      term1: r.term1,
      academic_year: r.academic_year
    }));
    const payload = {
      student: {
        full_name: student.full_name,
        class: student.classes?.name ?? null,
        registration_number
      },
      results
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list_attendance.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_attendance_default = defineTool4({
  name: "list_attendance",
  title: "List attendance",
  description: "List attendance records for a given date, optionally filtered by class name. Returns student, class, status.",
  inputSchema: {
    date: z3.string().describe("Attendance date in YYYY-MM-DD format."),
    class_name: z3.string().optional().describe("Optional class name filter.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ date, class_name }, ctx) => {
    const gate = await requireAdmin(ctx);
    if (gate) return gate;
    const supabase = createClient5(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("attendance").select("status, date, students(full_name, registration_number), classes(name)").eq("date", date);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((r) => ({
      full_name: r.students?.full_name,
      registration_number: r.students?.registration_number,
      class: r.classes?.name,
      status: r.status,
      date: r.date
    })).filter((r) => !class_name || (r.class ?? "").toLowerCase() === class_name.toLowerCase());
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { attendance: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/list_fees.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_fees_default = defineTool5({
  name: "list_fees",
  title: "List fees",
  description: "List fee records, optionally filtered by class name or payment status (paid/unpaid).",
  inputSchema: {
    class_name: z4.string().optional().describe("Optional class name filter."),
    status: z4.enum(["paid", "unpaid"]).optional().describe("Filter by payment status.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ class_name, status }, ctx) => {
    const gate = await requireAdmin(ctx);
    if (gate) return gate;
    const supabase = createClient6(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("fees").select("amount, status, students(full_name, registration_number, classes(name))");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((r) => ({
      full_name: r.students?.full_name,
      registration_number: r.students?.registration_number,
      class: r.students?.classes?.name,
      amount: r.amount,
      status: r.status
    })).filter((r) => !class_name || (r.class ?? "").toLowerCase() === class_name.toLowerCase()).filter((r) => !status || r.status === status);
    const total = rows.reduce((sum, r) => sum + (Number(r.amount) || 0), 0);
    const paid = rows.filter((r) => r.status === "paid").reduce((sum, r) => sum + (Number(r.amount) || 0), 0);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { fees: rows, count: rows.length, total_amount: total, paid_amount: paid }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "acejaexixsbfpwpugdxa";
var mcp_default = defineMcp({
  name: "almaqaasid-mcp",
  title: "Al-Maqaasid School MCP",
  version: "0.1.0",
  instructions: "Read-only access to Al-Maqaasid School data for authenticated admins: students, classes, results (Term 1), attendance, and fees. Requires the signed-in user to have the admin role.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_students_default, list_classes_default, get_student_results_default, list_attendance_default, list_fees_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
